EGamma_Run2023C:
  era: '2023'
  type: data
  group: data
  db: [das:/EGamma1/Run2023C-22Sep2023_v1-v1/NANOAOD,
       das:/EGamma1/Run2023C-22Sep2023_v2-v1/NANOAOD,
       das:/EGamma1/Run2023C-22Sep2023_v3-v1/NANOAOD,
       das:/EGamma1/Run2023C-22Sep2023_v4-v1/NANOAOD]
  run_range: &runs_23C [367094,367515]
  certified_lumi_file: &lumi_cert_23C https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions23/Cert_Collisions2023_eraC_367095_368823_Golden.json
  split: &nsplit -2
  
ZGto2NuG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/ZGto2NuG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: ZGto2NuG
  cross-section: 0.5646
  generated-events: genEventSumw
  split: *nsplit 

ZGto2NuG-1Jets_PTG-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/ZGto2NuG-1Jets_PTG-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: ZGto2NuG
  cross-section: 0.07472
  generated-events: genEventSumw
  split: *nsplit

ZGto2NuG-1Jets_PTG-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/ZGto2NuG-1Jets_PTG-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: ZGto2NuG
  cross-section: 0.005601
  generated-events: genEventSumw
  split: *nsplit

ZGto2NuG-1Jets_PTG-600to_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/ZGto2NuG-1Jets_PTG-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: ZGto2NuG
  cross-section: 0.00161
  generated-events: genEventSumw
  split: *nsplit

WGtoLNuG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/WGtoLNuG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v15-v2/NANOAODSIM
  type: mc
  group: WG
  cross-section: 2.209
  generated-events: genEventSumw
  split: *nsplit

WGtoLNuG-1Jets_PTG-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/WGtoLNuG-1Jets_PTG-200to400_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: WG
  cross-section: 0.2841
  generated-events: genEventSumw
  split: *nsplit

WGtoLNuG-1Jets_PTG-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/WGtoLNuG-1Jets_PTG-400to600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: WG
  cross-section: 0.0223
  generated-events: genEventSumw
  split: *nsplit
  
WGtoLNuG-1Jets_PTG-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  era: '2023'
  db: das:/WGtoLNuG-1Jets_PTG-600_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v3/NANOAODSIM
  type: mc
  group: WG
  cross-section: 0.004802
  generated-events: genEventSumw
  split: *nsplit
  
TTG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFXold-pythia8:
  era: '2023'
  db: das:/TTG-1Jets_PTG-100to200_TuneCP5_13p6TeV_amcatnloFXFXold-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v15-v2/NANOAODSIM
  type: mc
  group: TTG
  cross-section: 0.4205
  generated-events: genEventSumw
  split: *nsplit

TTG-1Jets_PTG-200_TuneCP5_13p6TeV_amcatnloFXFXold-pythia8:
  era: '2023'
  db: das:/TTG-1Jets_PTG-200_TuneCP5_13p6TeV_amcatnloFXFXold-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v15-v2/NANOAODSIM
  type: mc
  group: TTG
  cross-section: 0.1286
  generated-events: genEventSumw
  split: *nsplit

WW_TuneCP5_13p6TeV_pythia8:
  era: '2023'
  db: das:/WW_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-JMENano12p5_132X_mcRun3_2023_realistic_v5-v1/NANOAODSIM
  type: mc
  group: WW
  cross-section: 80.17
  generated-events: genEventSumw
  split: *nsplit

WZ_TuneCP5_13p6TeV_pythia8:
  era: '2023'
  db: das:/WZ_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: WZ
  cross-section: 29.20
  generated-events: genEventSumw
  split: *nsplit

ZZ_TuneCP5_13p6TeV_pythia8:
  era: '2023'
  db: das:/ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
  type: mc
  group: ZZ
  cross-section: 12.85
  generated-events: genEventSumw
  split: *nsplit